# Architecture identifier.
arch = "x86_64"
# Platform identifier.
platform = "x86_64-massdatas-gxxa203"
# Platform family.
family = "x86-pc"

# Base address of the whole physical memory.
phys-memory-base = "0x1_0080_0000"
# Size of the whole physical memory.
phys-memory-size = "0x3e0_0000"
# Base physical address of the kernel image.
kernel-base-paddr = "0x1_0080_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0x200000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0"

# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0xfec0_0000", "0x1000"],      # IO APIC
    ["0xfed0_0000", "0x1000"],      # HPET
    ["0xfee0_0000", "0x1000"],      # Local APIC
    ["0xf000_0000", "0x0800_0000"], # PCI config space
]
# VirtIO MMIO regions with format (`base_paddr`, `size`).
virtio-mmio-regions = []
# Base physical address of the PCIe ECAM space (should read from ACPI 'MCFG' table).
pci-ecam-base = "0xf000_0000"
# End PCI bus number.
pci-bus-end = "0x7f"
# PCI device memory ranges (not used on x86).
pci-ranges = []

# Timer interrupt frequencyin Hz.
timer-frequency = "4_000_000_000"   # 4.0GHz
